kind: Deployment
apiVersion: apps/v1
metadata:
   name: photogenic
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: photogenic
   template:
      metadata:
        labels:
          app: photogenic
      spec:
       containers:
        - name: photogenic
          image: ramakrishna8254/webserverhttp
          imagePullPolicy: Always
          ports:
          - containerPort: 80
