kind: Service                             
apiVersion: v1
metadata:
  name: photogenic
  labels:
    app: photogenic
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: photogenic                    
  type: LoadBalancer                   
