kind: Service                             
apiVersion: v1
metadata:
  name: webhttp
  labels:
    app: webhttp
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: webhttp                    
  type: LoadBalancer                   
